// 每日岗位数据 - 2026-07-04
// 此文件由每日搜集任务自动生成，请勿手动修改
const JOBS_DATA = {
  date: "2026-07-04",
  total: 90,
  lastUpdated: "2026-07-04T04:00:00Z",
  top5: [
    {
      company: "安克创新",
      title: "品牌经理（欧洲市场）",
      city: "深圳",
      salary: "25-45k·15薪",
      type: "品牌营销",
      exp: "3-5年",
      keywords: ["品牌", "欧洲", "出海"],
      score: 98,
      url: "https://career.anker-in.com",
      status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    {
      company: "小红书",
      title: "达人营销专家",
      city: "上海",
      salary: "20-35k·15薪",
      type: "品牌营销",
      exp: "3-5年",
      keywords: ["KOL", "内容营销", "种草"],
      score: 96,
      url: "https://job.xiaohongshu.com",
      status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    {
      company: "字节跳动",
      title: "抖音搜索营销产品运营经理",
      city: "上海",
      salary: "20-40k·15薪",
      type: "产品运营",
      exp: "3-5年",
      keywords: ["电商", "搜索", "增长", "抖音"],
      score: 95,
      url: "https://jobs.bytedance.com",
      status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    {
      company: "腾讯",
      title: "微信小店-产品运营-行业运营",
      city: "广州",
      salary: "20-40k·14薪",
      type: "产品运营",
      exp: "2-5年",
      keywords: ["微信", "电商", "行业运营"],
      score: 93,
      url: "https://careers.tencent.com",
      status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    {
      company: "安克创新",
      title: "GTM Manager（Regional）",
      city: "海外多地",
      salary: "30-50k·15薪",
      type: "产品运营",
      exp: "3-5年",
      keywords: ["GTM", "产品上市", "区域"],
      score: 92,
      url: "https://career.anker-in.com",
      status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" }
  ],
  jobs: [
    // 字节跳动
    { id: "bytedance-1", company: "字节跳动", title: "抖音搜索营销产品运营经理-电商搜索", city: "上海", salary: "20-40k·15薪", type: "产品运营", exp: "3-5年", keywords: ["电商", "搜索", "增长", "抖音"], score: 95, url: "https://jobs.bytedance.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "bytedance-2", company: "字节跳动", title: "招商运营（行业IP方向）-广告业务", city: "上海", salary: "20-40k·15薪", type: "品牌营销", exp: "3-5年", keywords: ["品牌IP", "招商", "商业化"], score: 92, url: "https://jobs.bytedance.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "bytedance-3", company: "字节跳动", title: "内容营销-抖音文创", city: "北京", salary: "20-40k·15薪", type: "品牌营销", exp: "3-5年", keywords: ["内容营销", "抖音", "文创"], score: 88, url: "https://jobs.bytedance.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "bytedance-4", company: "字节跳动", title: "营销活动专家（服务零售方向）", city: "北京", salary: "25-50k·15薪", type: "品牌营销", exp: "3-5年", keywords: ["本地生活", "零售", "营销"], score: 88, url: "https://jobs.bytedance.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "bytedance-5", company: "字节跳动", title: "广告营销策划-美妆/日化/服饰", city: "上海", salary: "20-40k", type: "品牌营销", exp: "3-5年", keywords: ["广告", "快消", "品牌策划"], score: 85, url: "https://jobs.bytedance.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "bytedance-6", company: "字节跳动", title: "高级营销产品经理", city: "北京", salary: "30-50k·15薪", type: "产品", exp: "5-8年", keywords: ["营销产品", "B端"], score: 78, url: "https://jobs.bytedance.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "bytedance-7", company: "字节跳动", title: "数据科学-TikTok", city: "上海", salary: "面议", type: "数据分析", exp: "3-5年", keywords: ["TikTok", "国际化", "数据"], score: 85, url: "https://jobs.bytedance.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "bytedance-8", company: "字节跳动", title: "数据科学（Global Selling）-TikTok Shop", city: "上海", salary: "面议", type: "数据分析", exp: "3-5年", keywords: ["电商", "跨境", "数据"], score: 87, url: "https://jobs.bytedance.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "bytedance-9", company: "字节跳动", title: "AI产品经理-TRAE", city: "上海", salary: "面议", type: "产品", exp: "3-5年", keywords: ["AI", "产品", "工具"], score: 83, url: "https://jobs.bytedance.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "bytedance-10", company: "字节跳动", title: "基础策略产品经理-懂车帝", city: "上海", salary: "面议", type: "产品", exp: "3-5年", keywords: ["汽车", "策略", "产品"], score: 80, url: "https://jobs.bytedance.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "bytedance-11", company: "字节跳动", title: "营销专员-懂车帝", city: "广州", salary: "面议", type: "品牌营销", exp: "1-3年", keywords: ["汽车", "营销"], score: 75, url: "https://jobs.bytedance.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "bytedance-12", company: "字节跳动", title: "搜索策略产品工程师-抖音", city: "深圳", salary: "面议", type: "产品", exp: "3-5年", keywords: ["搜索", "策略", "产品"], score: 82, url: "https://jobs.bytedance.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    // 小红书
    { id: "xhs-1", company: "小红书", title: "达人营销专家", city: "上海", salary: "20-35k·15薪", type: "品牌营销", exp: "3-5年", keywords: ["KOL", "内容营销", "种草"], score: 96, url: "https://job.xiaohongshu.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "xhs-2", company: "小红书", title: "商业化跨境业务-平台专家", city: "上海", salary: "30-50k·15薪", type: "运营", exp: "5-8年", keywords: ["跨境", "商业化", "广告"], score: 82, url: "https://job.xiaohongshu.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "xhs-3", company: "小红书", title: "产品运营经理", city: "上海", salary: "20-35k·15薪", type: "产品运营", exp: "3-5年", keywords: ["产品", "运营", "社区"], score: 90, url: "https://job.xiaohongshu.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "xhs-4", company: "小红书", title: "内容运营", city: "上海", salary: "18-30k·15薪", type: "内容运营", exp: "1-3年", keywords: ["内容", "社区", "UGC"], score: 88, url: "https://job.xiaohongshu.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "xhs-5", company: "小红书", title: "电商运营", city: "上海", salary: "18-30k·15薪", type: "电商运营", exp: "1-3年", keywords: ["电商", "运营", "品牌"], score: 86, url: "https://job.xiaohongshu.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "xhs-6", company: "小红书", title: "Growth Hacker增长营销/产品/运营", city: "上海", salary: "20-40k·15薪", type: "增长运营", exp: "3-5年", keywords: ["增长", "营销", "数据分析"], score: 92, url: "https://job.xiaohongshu.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "xhs-7", company: "小红书", title: "用户研究", city: "上海", salary: "18-30k·15薪", type: "用户研究", exp: "3-5年", keywords: ["用户", "研究", "洞察"], score: 80, url: "https://job.xiaohongshu.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "xhs-8", company: "小红书", title: "视觉设计", city: "上海", salary: "18-30k·15薪", type: "设计", exp: "3-5年", keywords: ["视觉", "设计", "品牌"], score: 75, url: "https://job.xiaohongshu.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "xhs-9", company: "小红书", title: "市场营销", city: "上海", salary: "20-35k·15薪", type: "品牌营销", exp: "3-5年", keywords: ["市场", "品牌", "营销"], score: 90, url: "https://job.xiaohongshu.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "xhs-10", company: "小红书", title: "数据科学", city: "上海", salary: "20-35k·15薪", type: "数据分析", exp: "3-5年", keywords: ["数据", "分析", "洞察"], score: 82, url: "https://job.xiaohongshu.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    // 腾讯
    { id: "tencent-1", company: "腾讯", title: "微信小店-产品运营-行业运营", city: "广州", salary: "20-40k·14薪", type: "产品运营", exp: "2-5年", keywords: ["微信", "电商", "行业运营"], score: 93, url: "https://careers.tencent.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "tencent-2", company: "腾讯", title: "微信读书/秒剪/输入法-AI产品", city: "广州", salary: "20-40k·14薪", type: "产品", exp: "3-5年", keywords: ["AI", "产品", "微信生态"], score: 88, url: "https://careers.tencent.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "tencent-3", company: "腾讯", title: "Operations Lead-AI Creator Platform", city: "洛杉矶", salary: "97k-183k USD", type: "产品运营", exp: "4-7年", keywords: ["AI", "创作者平台", "运营"], score: 72, url: "https://careers.tencent.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "tencent-4", company: "腾讯", title: "AI Script Editor & Screenwriter", city: "洛杉矶", salary: "80k-134k USD", type: "内容创作", exp: "1-5年", keywords: ["AI", "短剧", "编剧"], score: 70, url: "https://careers.tencent.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "tencent-5", company: "腾讯", title: "Cloud Media Services Intern", city: "帕罗奥多", salary: "27-51 USD/h", type: "产品", exp: "实习", keywords: ["音视频", "云", "产品"], score: 65, url: "https://careers.tencent.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "tencent-6", company: "腾讯", title: "游戏产品商业化运营", city: "上海", salary: "20-40k·14薪", type: "游戏运营", exp: "2-5年", keywords: ["游戏", "商业化", "FPS"], score: 78, url: "https://careers.tencent.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "tencent-7", company: "腾讯", title: "电商平台营销活动策略与执行", city: "广州", salary: "20-35k·14薪", type: "产品运营", exp: "3-5年", keywords: ["电商", "活动", "策略"], score: 85, url: "https://careers.tencent.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "tencent-8", company: "腾讯", title: "童装童鞋热招品牌引入和运营", city: "广州", salary: "18-30k·14薪", type: "电商运营", exp: "3-5年", keywords: ["品牌", "电商", "微信"], score: 80, url: "https://careers.tencent.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "tencent-9", company: "腾讯", title: "广告商业化产品运营经理", city: "深圳", salary: "15-30k·14薪", type: "产品运营", exp: "3-5年", keywords: ["广告", "商业化", "产品"], score: 82, url: "https://careers.tencent.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "tencent-10", company: "腾讯", title: "Senior Researcher（LLM for Gaming）", city: "帕罗奥多", salary: "118k-274k USD", type: "技术/AI", exp: "5年+", keywords: ["大模型", "游戏AI", "NLP"], score: 68, url: "https://careers.tencent.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    // 阿里
    { id: "alibaba-1", company: "阿里巴巴", title: "阿里巴巴国际站-直播内容运营", city: "杭州", salary: "35-55k·16薪", type: "内容运营", exp: "5-10年", keywords: ["直播", "内容", "国际化"], score: 78, url: "https://talent.alibaba.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "alibaba-2", company: "阿里巴巴", title: "阿里巴巴国际站-业务策略运营", city: "杭州", salary: "35-60k·15薪", type: "运营", exp: "5年+", keywords: ["策略", "运营", "销售"], score: 75, url: "https://talent.alibaba.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "alibaba-3", company: "阿里巴巴", title: "阿里巴巴国际站-欧洲用户运营专家", city: "杭州", salary: "35-55k·15薪", type: "用户运营", exp: "5-10年", keywords: ["用户运营", "欧洲", "国际化"], score: 80, url: "https://talent.alibaba.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "alibaba-4", company: "阿里巴巴", title: "阿里巴巴国际站-商品运营", city: "杭州", salary: "35-55k·15薪", type: "电商运营", exp: "5年+", keywords: ["商品", "电商", "运营"], score: 78, url: "https://talent.alibaba.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "alibaba-5", company: "阿里巴巴", title: "淘宝-品牌营销", city: "杭州", salary: "25-45k·16薪", type: "品牌营销", exp: "3-5年", keywords: ["品牌", "营销", "电商"], score: 88, url: "https://talent.alibaba.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "alibaba-6", company: "阿里巴巴", title: "天猫-行业运营", city: "杭州", salary: "25-45k·16薪", type: "行业运营", exp: "3-5年", keywords: ["行业", "运营", "天猫"], score: 85, url: "https://talent.alibaba.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "alibaba-7", company: "阿里巴巴", title: "阿里云-产品运营", city: "杭州", salary: "25-45k·16薪", type: "产品运营", exp: "3-5年", keywords: ["云", "产品", "运营"], score: 80, url: "https://talent.alibaba.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "alibaba-8", company: "阿里巴巴", title: "盒马-品牌运营", city: "上海", salary: "20-35k·14薪", type: "品牌运营", exp: "3-5年", keywords: ["品牌", "新零售", "运营"], score: 82, url: "https://talent.alibaba.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    // 美团
    { id: "meituan-1", company: "美团", title: "快驴-进向-杭州运营主管", city: "杭州", salary: "8-13k·13薪", type: "运营", exp: "3-5年", keywords: ["供应链", "运营", "餐饮"], score: 72, url: "https://zhaopin.meituan.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "meituan-2", company: "美团", title: "美团外卖-品牌运营", city: "北京", salary: "20-35k·15薪", type: "品牌运营", exp: "3-5年", keywords: ["品牌", "外卖", "本地生活"], score: 85, url: "https://zhaopin.meituan.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "meituan-3", company: "美团", title: "美团到店-产品运营", city: "北京", salary: "20-35k·15薪", type: "产品运营", exp: "3-5年", keywords: ["产品", "到店", "本地生活"], score: 83, url: "https://zhaopin.meituan.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "meituan-4", company: "美团", title: "美团优选-品类运营", city: "北京", salary: "18-30k·15薪", type: "品类运营", exp: "3-5年", keywords: ["品类", "电商", "社区团购"], score: 80, url: "https://zhaopin.meituan.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "meituan-5", company: "美团", title: "美团酒旅-营销运营", city: "北京", salary: "20-35k·15薪", type: "营销运营", exp: "3-5年", keywords: ["营销", "酒旅", "本地生活"], score: 82, url: "https://zhaopin.meituan.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "meituan-6", company: "美团", title: "美团买菜-用户增长运营", city: "上海", salary: "18-30k·15薪", type: "增长运营", exp: "3-5年", keywords: ["用户增长", "买菜", "电商"], score: 85, url: "https://zhaopin.meituan.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "meituan-7", company: "美团", title: "美团充电宝-商务运营", city: "深圳", salary: "15-25k·15薪", type: "商务运营", exp: "1-3年", keywords: ["商务", "运营", "硬件"], score: 75, url: "https://zhaopin.meituan.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "meituan-8", company: "美团", title: "美团-数据运营", city: "北京", salary: "20-35k·15薪", type: "数据运营", exp: "3-5年", keywords: ["数据", "运营", "分析"], score: 80, url: "https://zhaopin.meituan.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    // 安克创新
    { id: "anker-1", company: "安克创新", title: "品牌经理（欧洲市场）", city: "深圳", salary: "25-45k·15薪", type: "品牌营销", exp: "3-5年", keywords: ["品牌", "欧洲", "出海"], score: 98, url: "https://career.anker-in.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "anker-2", company: "安克创新", title: "GTM Manager（Regional）", city: "海外多地", salary: "30-50k·15薪", type: "产品运营", exp: "3-5年", keywords: ["GTM", "产品上市", "区域"], score: 92, url: "https://career.anker-in.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "anker-3", company: "安克创新", title: "海外电商运营专员", city: "长沙", salary: "15-25k·15薪", type: "电商运营", exp: "1-3年", keywords: ["跨境电商", "亚马逊", "运营"], score: 88, url: "https://career.anker-in.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "anker-4", company: "安克创新", title: "媒介专员", city: "深圳", salary: "15-25k·15薪", type: "品牌营销", exp: "1-3年", keywords: ["媒介", "投放", "广告"], score: 82, url: "https://career.anker-in.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "anker-5", company: "安克创新", title: "CRM专员（中国区）", city: "深圳", salary: "15-25k·15薪", type: "用户运营", exp: "1-3年", keywords: ["CRM", "用户运营", "社群"], score: 80, url: "https://career.anker-in.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "anker-6", company: "安克创新", title: "Sales Specialist", city: "日本/欧洲", salary: "20-35k·15薪", type: "销售", exp: "1-3年", keywords: ["销售", "小语种", "国际化"], score: 78, url: "https://career.anker-in.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "anker-7", company: "安克创新", title: "产品经理", city: "深圳", salary: "20-35k·15薪", type: "产品", exp: "3-5年", keywords: ["产品", "消费电子", "硬件"], score: 85, url: "https://career.anker-in.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "anker-8", company: "安克创新", title: "营销族-管培生", city: "深圳/长沙", salary: "15-25k·15薪", type: "品牌营销", exp: "应届生", keywords: ["营销", "管培", "出海"], score: 88, url: "https://career.anker-in.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "anker-9", company: "安克创新", title: "技术族-管培生", city: "深圳/长沙", salary: "18-30k·15薪", type: "技术", exp: "应届生", keywords: ["技术", "硬件", "研发"], score: 75, url: "https://career.anker-in.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "anker-10", company: "安克创新", title: "设计族-管培生", city: "深圳", salary: "15-25k·15薪", type: "设计", exp: "应届生", keywords: ["设计", "产品", "创意"], score: 78, url: "https://career.anker-in.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    // SHEIN
    { id: "shein-1", company: "SHEIN", title: "品牌运营专员", city: "深圳", salary: "18-30k·14薪", type: "品牌运营", exp: "1-3年", keywords: ["品牌", "运营", "快时尚"], score: 90, url: "https://careers.shein.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "shein-2", company: "SHEIN", title: "买手", city: "广州", salary: "15-25k·14薪", type: "买手", exp: "1-3年", keywords: ["买手", "时尚", "供应链"], score: 78, url: "https://careers.shein.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "shein-3", company: "SHEIN", title: "企划", city: "广州", salary: "18-30k·14薪", type: "企划", exp: "3-5年", keywords: ["企划", "商品", "时尚"], score: 80, url: "https://careers.shein.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "shein-4", company: "SHEIN", title: "招商运营", city: "广州", salary: "18-30k·14薪", type: "招商运营", exp: "3-5年", keywords: ["招商", "运营", "商家"], score: 82, url: "https://careers.shein.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "shein-5", company: "SHEIN", title: "国际物流与仓储运营", city: "广州", salary: "15-25k·14薪", type: "物流运营", exp: "3-5年", keywords: ["物流", "仓储", "国际"], score: 75, url: "https://careers.shein.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "shein-6", company: "SHEIN", title: "全球运营管培生", city: "广州/深圳", salary: "15-25k·14薪", type: "运营", exp: "应届生", keywords: ["运营", "管培", "全球"], score: 85, url: "https://careers.shein.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "shein-7", company: "SHEIN", title: "设计师", city: "广州", salary: "18-30k·14薪", type: "设计", exp: "1-3年", keywords: ["设计", "服装", "时尚"], score: 76, url: "https://careers.shein.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "shein-8", company: "SHEIN", title: "服装供应链专员", city: "广州", salary: "15-25k·14薪", type: "供应链", exp: "3-5年", keywords: ["供应链", "服装", "生产"], score: 72, url: "https://careers.shein.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    // 拼多多
    { id: "pdd-1", company: "拼多多", title: "市场管培生", city: "上海", salary: "15-25k·16薪", type: "品牌营销", exp: "应届生", keywords: ["市场", "管培", "品牌"], score: 85, url: "https://careers.pddglobalhr.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "pdd-2", company: "拼多多", title: "产品管培生", city: "上海", salary: "18-30k·16薪", type: "产品", exp: "应届生", keywords: ["产品", "管培", "电商"], score: 83, url: "https://careers.pddglobalhr.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "pdd-3", company: "拼多多", title: "招商运营管培生", city: "深圳", salary: "15-25k·16薪", type: "招商运营", exp: "应届生", keywords: ["招商", "运营", "商家"], score: 82, url: "https://careers.pddglobalhr.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "pdd-4", company: "拼多多", title: "品类运营管培生", city: "上海", salary: "15-25k·16薪", type: "品类运营", exp: "应届生", keywords: ["品类", "运营", "电商"], score: 80, url: "https://careers.pddglobalhr.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "pdd-5", company: "拼多多", title: "设计管培生（创意设计）", city: "上海", salary: "15-25k·16薪", type: "设计", exp: "应届生", keywords: ["设计", "创意", "视觉"], score: 76, url: "https://careers.pddglobalhr.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "pdd-6", company: "拼多多", title: "商家运营（多语种优势）", city: "深圳", salary: "15-25k·16薪", type: "商家运营", exp: "应届生", keywords: ["商家", "小语种", "跨境"], score: 78, url: "https://careers.pddglobalhr.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    // 大疆
    { id: "dji-1", company: "大疆", title: "品牌运营经理", city: "深圳", salary: "20-35k·15薪", type: "品牌运营", exp: "3-5年", keywords: ["品牌", "无人机", "出海"], score: 88, url: "https://we.dji.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "dji-2", company: "大疆", title: "海外社媒运营", city: "深圳", salary: "18-30k·15薪", type: "社媒运营", exp: "3-5年", keywords: ["社媒", "海外", "内容"], score: 85, url: "https://we.dji.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "dji-3", company: "大疆", title: "产品经理-消费级", city: "深圳", salary: "25-45k·15薪", type: "产品", exp: "3-5年", keywords: ["产品", "无人机", "硬件"], score: 82, url: "https://we.dji.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "dji-4", company: "大疆", title: "国际化运营", city: "深圳", salary: "20-35k·15薪", type: "运营", exp: "3-5年", keywords: ["国际化", "运营", "出海"], score: 86, url: "https://we.dji.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    // Temu
    { id: "temu-1", company: "Temu", title: "品牌运营", city: "广州", salary: "18-30k·16薪", type: "品牌运营", exp: "3-5年", keywords: ["品牌", "跨境", "电商"], score: 85, url: "https://careers.pddglobalhr.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "temu-2", company: "Temu", title: "海外增长运营", city: "广州", salary: "20-35k·16薪", type: "增长运营", exp: "3-5年", keywords: ["增长", "海外", "用户"], score: 86, url: "https://careers.pddglobalhr.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "temu-3", company: "Temu", title: "商家运营", city: "广州", salary: "18-30k·16薪", type: "商家运营", exp: "3-5年", keywords: ["商家", "运营", "跨境"], score: 82, url: "https://careers.pddglobalhr.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "temu-4", company: "Temu", title: "品类运营", city: "广州", salary: "18-30k·16薪", type: "品类运营", exp: "3-5年", keywords: ["品类", "运营", "电商"], score: 80, url: "https://careers.pddglobalhr.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    // 华为
    { id: "huawei-1", company: "华为", title: "终端品牌运营", city: "深圳", salary: "20-35k·15薪", type: "品牌运营", exp: "3-5年", keywords: ["品牌", "终端", "手机"], score: 86, url: "https://career.huawei.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "huawei-2", company: "华为", title: "消费者洞察分析师", city: "深圳", salary: "20-35k·15薪", type: "用户研究", exp: "3-5年", keywords: ["用户", "洞察", "分析"], score: 82, url: "https://career.huawei.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "huawei-3", company: "华为", title: "海外营销", city: "深圳/海外", salary: "25-45k·15薪", type: "营销", exp: "3-5年", keywords: ["海外", "营销", "品牌"], score: 88, url: "https://career.huawei.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "huawei-4", company: "华为", title: "产品运营经理", city: "深圳", salary: "20-35k·15薪", type: "产品运营", exp: "3-5年", keywords: ["产品", "运营", "生态"], score: 83, url: "https://career.huawei.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    // 小米
    { id: "xiaomi-1", company: "小米", title: "品牌运营", city: "北京", salary: "18-30k·14薪", type: "品牌运营", exp: "3-5年", keywords: ["品牌", "手机", "生态链"], score: 84, url: "https://hr.xiaomi.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "xiaomi-2", company: "小米", title: "产品运营-IoT", city: "北京", salary: "18-30k·14薪", type: "产品运营", exp: "3-5年", keywords: ["产品", "IoT", "智能家居"], score: 82, url: "https://hr.xiaomi.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "xiaomi-3", company: "小米", title: "海外电商运营", city: "北京", salary: "18-30k·14薪", type: "电商运营", exp: "3-5年", keywords: ["电商", "海外", "跨境"], score: 85, url: "https://hr.xiaomi.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    // OPPO
    { id: "oppo-1", company: "OPPO", title: "品牌策划", city: "深圳", salary: "18-30k·14薪", type: "品牌营销", exp: "3-5年", keywords: ["品牌", "手机", "策划"], score: 83, url: "https://careers.oppo.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "oppo-2", company: "OPPO", title: "海外社媒运营", city: "深圳", salary: "18-30k·14薪", type: "社媒运营", exp: "3-5年", keywords: ["社媒", "海外", "内容"], score: 82, url: "https://careers.oppo.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" },
    { id: "oppo-3", company: "OPPO", title: "产品运营", city: "深圳", salary: "18-30k·14薪", type: "产品运营", exp: "3-5年", keywords: ["产品", "运营", "手机"], score: 80, url: "https://careers.oppo.com", status: "", desc: "", jd: "暂无详细JD", source: "", link: "", email: "" }
  ]
};

if (typeof module !== 'undefined') {
  module.exports = JOBS_DATA;
}
